### ISSUE TITLE
blockParse.py overlapping probes 

### ISSUE THREAD

**Issue by jonathanperrie** [brianbeliveau/OligoMiner#20]
https://github.com/beliveau-lab/OligoMiner/blob/master/blockParse.py#L672

Can the spacing be set to a negative number to encourage there to be some level of overlap? I tried making a minor adaptation to have this work while accounting for indices below the length of the length of a probe and it just hung

**Comment by brianbeliveau** [comment]
Yes, just flag '-O' or '--OverlapMode and the spacing parameter will be ignored. There is currently no way to tune the amount of overlap allowed, but if that is desired one could simply parse the output and filter from there (eg with pandas or bedtools)
