### ISSUE TITLE
How to find probes with Tm between 69/73 °C

### ISSUE THREAD

**Issue by a-velt** [brianbeliveau/OligoMiner#22]
Hi,

I would need to design probes for my virus genome, with a Tm between 69 and 73°C. This Tm is needed for the protocol I use.

I tried a lot of options with blockParse.py but everything comes out to me as 0 candidate.

Here is an example of command line : 

python2.7 OligoMiner/blockParse.py -f virus.fasta -t 69 -T 73 -L 50 -l 40 --min_GC 0 --max_GC 100

I specify the Tm range I want, between 69 and 73°C .Simply with these options, I had 0 candidate. So I tried to increase the size of my probes with the "-l" and "-L" options. I also tried to increase the possible range of the %GC. But each time I have 0 candidate. Do you have any advice on how to find these probes with a Tm between 69/73°C?

Thank you very much !
Have a nice day.
Amandine

**Comment by brianbeliveau** [comment]
Hi, 

Can you please verify that this issue disappears if you use the default Tm settings? This would help rule out issues with your input file.

Also, please be advised that by default blockParse assumes that 50% formamide is being used and adjusts the effective temperature accordingly. A sequence would need to be quite long (~80+ nt) and GC rich to have a Tm in the 69–73ºC range in 50% formamide. You can change formamide with "-F"

**Comment by a-velt** [comment]
Hi,

Yes OligoMiner was working with the default settings.

I changed the % formamide and it's OK!! Thank you very much, I had not paid attention to this option.

Thank you for your help !
Have a nice day,
Amandine

**Comment by brianbeliveau** [comment]
Great!
