### ISSUE TITLE
Error in installation of packages

### ISSUE THREAD

**Issue by nbrownstein** [brianbeliveau/OligoMiner#23]
Hi,

I am not a very computer savvy user here. I am on a windows 10 machine. When I put the command conda env create -f environment.yml into the miniconda command line it gives me the following output: 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - bowtie2=2.3.5.1
  - scikit-learn=0.20.4
  - jellyfish=2.2.10
  - nupack=3.0.6

As far as I can tell conda cannot find these programs to download. Looking forward to using this tool, any help is appreciated!

**Comment by conorcamplisson** [comment]
It looks there are no conda builds for those package versions on Windows OS. I recommend enabling the windows subsystem for linux (WSL) and installing Ubuntu. You can then create the conda env in a ubuntu terminal (after installing miniconda within ubuntu) and the Linux conda builds will be used. There is more info about this here:

https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview
