### ISSUE TITLE
How to obtain/design nongenomic sequence?

### ISSUE THREAD

**Issue by ShixiangWang** [brianbeliveau/OligoMiner#24]
Hi developers,

Thanks for developing this tool and useful resources. I checked the known probes provided by https://oligopaints.hms.harvard.edu/genome-files and found that only the genome sequence is provided.

However, from https://github.com/gnir/OligoLego, it describes the a whole probe should include nongenomic sequences at their 5' and/or 3' ends. How should I obtain or design such sequence for actual experiments? 

> Oligopaints - Oligopaint probes consist of computationally designed single-stranded oligos that can target their genomic complements while avoiding repeated sequences (Brian J. Beliveau et al. PNAS 2012; Nat. Comms. 2015). They carry a region of genomic homology that is generally ~32-42 bases long, and carry nongenomic sequences at their 5' and/or 3' ends. These regions, called Mainstreet and Backstreet, respectively, augment the cost-effectiveness of Oligopaints by enabling the libraries to be renewed through amplification or multiplexed through sublibrary-specific primer and barcodes sequences. Universal - a 20 nt universal PCR primer sequence at both ends of each Oligopaint oligo, which acts as a simple tool to amplify an entire Oligopaints library at once.

Best,

Shixiang

**Comment by brianbeliveau** [comment]
Hi,

Please see https://github.com/beliveau-lab/PaintSHOP_resources#appending-sequence-files

**Comment by ShixiangWang** [comment]
Thanks a lot
