### ISSUE TITLE
Installing nupack in a server environment without root access

### ISSUE THREAD

**Issue by scottsisco** [brianbeliveau/OligoMiner#3]
The install instructions to get structureCheck.py to function in a server environment where the user does not have root access asks the user to compile nupack in the users home folder using the following commands.

    /.configure --prefix=$HOME
    make
    make install 

However, I have downloaded and extracted both nupack3.0.6.tar.gz and nupack3.0.4.tar.gz from http://nupack.org/downloads/source and both seem to be missing the .configure file.  Am I missing something? Any help will be greatly appreciated. Thanks.

**Comment by brianbeliveau** [comment]
Have looked into this, those instructions indeed do not seem to be correct for NUPACK 3.0.6.

I was just able to install on a CentOS server without root simply running 'make' ... this may work for you as well.

Thank you for brining this documentation error to our attention

**Comment by scottsisco** [comment]
Thank you for your quick response! Do you know if simply running 'make' will confine the install to the folder nupack is compiling from or will it install various pieces of the application in other directories like /usr/bin or /usr/sbin?

If you are not sure I can always spin up a VM and test for myself.

**Comment by brianbeliveau** [comment]
It should confine the install to the local folder, but the VM is a good idea if you want to be sure. 

I have verified that it is functioning after running 'make' and setting my PATH and NUPACKHOME env variables. 

Apologies for the confusion, and good luck!

**Comment by scottsisco** [comment]
I was able to get NUPACK to compile in a VM. However, on our server I was unable to get the software to compile properly. I should mention I am not installing Oligominer in my home folder, but in a folder that is accessible to all the scientists I work with.  I am installing the software at the request of one scientist in particular and she said NUPACK is not required so I'm going to leave it there for now. Maybe, in the future I can add it. :)

As an aside my I ask why none of your python scripts use a shebang line like the following "#!/usr/bin/env python" at the beginning of the script? I ended up adding the line to all the scripts so our scientists can run each script without including the python command when executing the script.

Thank you, for all your help!

**Comment by brianbeliveau** [comment]
Sorry to hear you are having issues with the NUPACK compilation. You may want to get in touch with the NUPACK team if you decide to revisit in the future: [http://www.nupack.org/home/contact](http://www.nupack.org/home/contact).

Re: the shebang line, this was left out mainly for simplicity. It can of course be added as you have done.
