### ISSUE TITLE
error in running outputClean.py

### ISSUE THREAD

**Issue by bostanict** [brianbeliveau/OligoMiner#5]
Hi,

after running the 

python ../OligoMiner/outputClean.py -u -f myfile_u.sam

I receive this error:

Traceback (most recent call last):
  File "../OligoMiner/outputClean.py", line 486, in <module>
    main()
  File "../OligoMiner/outputClean.py", line 480, in main
    reportVal, debugVal, metaVal, outNameVal, startTime)
  File "../OligoMiner/outputClean.py", line 70, in cleanOutput
    if x[0] is not '@' else ' ' for x in file_read]
IndexError: list index out of range

I ran it on the example sam file and it works but I am not sure why it is not working on mine. here is also the head of my sam file:

VCAEv1-Chr01    272     VCAEv1-Chr07    42194800        32      41M     *       0       0       GGTCAGATTGGCCTGATCTGTTTTCCATTCACACTACATAT       ~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:74 XS:i:74 XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:13A27      YT:Z:UU
VCAEv1-Chr01    0       VCAEv1-C41      1139    33      38M     *       0       0       AAAAGTATGCCTAAACTTCTTTGCCTCCCATCTGCTGA  ~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~     AS:i:76 XS:i:66 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:38 YT:Z:UU
VCAEv1-Chr01    272     VCAEv1-Chr07    42194759        33      16M1I21M        *       0       0       TCAGCAGATGGGAGGCAAAGAAGTTTAGGCATACTTTT  ~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     AS:i:66 XS:i:66 XN:i:0  XM:i:0  XO:i:1  XG:i:1  NM:i:1  MD:Z:37 YT:Z:UU
VCAEv1-Chr01    0       VCAEv1-C41      1177    1       36M     *       0       0       GTCCAAGTATTTGTATGCACAGCACAACAGTGAGGG    ~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~       AS:i:72 XS:i:72 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:36 YT:Z:UU
VCAEv1-Chr01    272     VCAEv1-Chr07    42194723        1       36M     *       0       0       CCCTCACTGTTGTGCTGTGCATACAAATACTTGGAC    ~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~       AS:i:72 XS:i:72 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:36 YT:Z:UU
VCAEv1-Chr01    0       VCAEv1-C41      1263    1       41M     *       0       0       AACTGATTCAGCTGTTTGTCTGCTTTTCCATACAATTGGTG       ~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:82 XS:i:82 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:41 YT:Z:UU
VCAEv1-Chr01    272     VCAEv1-Chr07    42194632        1       41M     *       0       0       CACCAATTGTATGGAAAAGCAGACAAACAGCTGAATCAGTT       ~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:82 XS:i:82 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:41 YT:Z:UU
VCAEv1-Chr01    0       VCAEv1-C41      1305    1       41M     *       0       0       TACCAGCATCCATACTGCAAAGACACAACTTTGTATAAGCA       ~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:82 XS:i:82 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:41 YT:Z:UU
VCAEv1-Chr01    272     VCAEv1-Chr07    42194590        1       41M     *       0       0       TGCTTATACAAAGTTGTGTCTTTGCAGTATGGATGCTGGTA       ~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:82 XS:i:82 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:41 YT:Z:UU
VCAEv1-Chr01    0       VCAEv1-C41      1394    1       40M     *       0       0       ATTGAAACAGTCCTTCTATTGTCAGTCCACTTTGCTGACA        ~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   AS:i:80 XS:i:80 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:40 YT:Z:UU
VCAEv1-Chr01    272     VCAEv1-Chr07    42194502        1       40M     *       0       0       TGTCAGCAAAGTGGACTGACAATAGAAGGACTGTTTCAAT        ~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   AS:i:80 XS:i:80 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:40 YT:Z:UU
VCAEv1-Chr01    0       VCAEv1-C41      1434    32      41M     *       0       0       ATAAGACAAGACTCTTGCATGGAAGAGTTAACTCTTGCACG       ~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:82 XS:i:74 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:41 YT:Z:UU
VCAEv1-Chr01    272     VCAEv1-Chr07    42194461        32      41M     *       0       0       CGTGCAAGAGTTAACTCTTCCATGCAAGAGTCTTGTCTTAT       ~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:74 XS:i:74 XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:28G12      YT:Z:UU
VCAEv1-Chr01    272     VCAEv1-Chr12    41323418        32      35M6S   *       0       0       CGTGCAAGAGTTAACTCTTCCATGCAAGAGTCTTGTCTTAT       ~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  AS:i:62 XS:i:74 XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:30C4       YT:Z:UU

**Comment by brianbeliveau** [comment]
Hi,

This error is likely because the header of the FASTA passed into blockParse
was not in chrom:start-stop format. I think if you either reformat your
FASTA ID line or use -H in blockParse to specify a custom one in the
aforementioned format this error will go away.

Hope that helps,

Brian

**Comment by bostanict** [comment]
Yes, thanks for the tip. It is working now but the other issue I am facing now is that the python blockParse.py -f genome.fa
only generates the fastq file with sequences from the first chromosome only. It does not generate the sequences for each chromosome. should I run it for each chromosome independently? if so, how can I know the probes are chromosome-specific?

**Comment by brianbeliveau** [comment]
blockParse does not currently support multi-entry FASTA files. You will
indeed need to run it separately for each chromosome in your genome. You
would still want to align against the whole genome at the next step though
... this will help ensure the resulting probes have only one genomic target.

**Comment by bostanict** [comment]
Thanks. SO after I did it for each chr, I merge them and run them for all the chromosomes. My aim is to design chromosome-specific probes for fish, so I have to run on all to find the unique ones, is that what you suggest too?

**Comment by brianbeliveau** [comment]
Apologies, I do not think I quite understand the question. Probes designed
using the approaches laid out in the PNAS paper should only have one
predicted binding site, so a set of them that collectively target a given
interval on a chromosome would be "chromosome-specific" as well as
interval-specific (i.e. they would not be predicted to bind another
interval on the same chromosome).

Does that help?

**Comment by bostanict** [comment]
Dear @brianbeliveau 

thanks a lot for the swift replies and sorry for my delay in responses. So my question is now that 

1- should I merge all the fastq files and map them to all the chromosomes?

2- now that I am trying to map them using the command in the wiki here as 👍 


bowtie2 -x genome -U genome.fastq --no-hd -t -k 100 --very-sensitive-local -S genome.fastq_u.sam

I am receiving this error:

Time loading reference: 00:00:00
Time loading forward index: 00:00:00
Time loading mirror index: 00:00:00
Error: Read VCAEv1_C01:490906-490946 has more quality values than read characters.
Multiseed full-index search: 00:00:02
Time searching: 00:00:02
Overall time: 00:00:02
Error: Encountered exception: 'Unidentified exception'
Command: /usr/bin/bowtie2-align-s --wrapper basic-0 -x genome --no-hd -t -k 100 --very-sensitive-local -S genome.fastq_u.sam -U genome.fastq
(ERR): bowtie2-align exited with value 1

**Comment by bostanict** [comment]
YES, thank you so much

**Comment by bostanict** [comment]
I got the final results from .OligoMiner/outputClean.py. I have the result for all the chromosomes but oddly, I see that 2 chromosomes out of 12 have the bed file empty. I tried to run them again and I got the following message for both of them:

outputClean identified 0 of 820994 / 0.0000% candidate probes as unique
Program took 962.568463 seconds

Is it normal?

**Comment by brianbeliveau** [comment]
Hmm, that doesn't seem quite right, but a lot could depend on what exactly
is in the genome assembly and .bt2 files you are using. I would recommend
looking at the .sam files in more detail
