### ISSUE TITLE
structureCheck.py cannot create multi-level temp dir

### ISSUE THREAD

**Issue by ArielPaulson** [brianbeliveau/OligoMiner#8]
Hi,

Temp dir creation needs to be "os.makedirs" not "os.mkdir", since input file may be have a path, which will cause the temp dir to be multi-level.  Currently the script cannot create multi-level temp dirs.

Example, inside "OligoMiner/ExampleFiles:" location: 
Run: "python ../structureCheck.py -f 3_probes.bed -t 0.4"  
Succeeds, because temp dir was only "/tmp/3_probes_432686".

Example, inside "OligoMiner" location:
Run: "python structureCheck.py -f ExampleFiles/3_probes.bed -t 0.4", 
Dies, because cannot create temp dir "/tmp/ExampleFiles/3_probes_839260".

However if I first run "mkdir /tmp/ExampleFiles" and then run the above command, it succeeds. 

Thanks,
Ariel

**Comment by brianbeliveau** [comment]
Logic updated to support multi-level temp dirs.
